namespace Tingle.EventBus.Diagnostics
{
    /// <summary>
    /// Names for activities generated by EventBus
    /// </summary>
    public static class ActivityNames
    {
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
        public const string Consume = "EventBus.Consume";
        public const string Publish = "EventBus.Publish";
        public const string Cancel = "EventBus.Cancel";
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
    }
}
