name: Validate PR

on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - README.md
    - LICENSE
    - CHANGELOG.md
    - docs/**

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: >
        dotnet build
        --configuration Release
        --no-restore

    - name: Test
      run: >
        dotnet test
        --configuration Release
        --no-build
        --verbosity normal
        --collect "Code coverage"
