name: Build and Publish

on:
  push:
    # branches:
    #   - main
    tags:
      - '*'
    paths-ignore:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - docs/**

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      buildConfiguration: 'Release'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Required for GitVersion

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          5.x
          6.x
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: >
        dotnet build
        --configuration $buildConfiguration
        --no-restore

    - name: Test
      run: >
        dotnet test
        --configuration $buildConfiguration
        --no-build
        --verbosity normal
        --collect "Code coverage"

    - name: Pack
      run: >
        dotnet pack
        --configuration $buildConfiguration
        --no-build
        --verbosity Detailed
        --output $GITHUB_WORKSPACE/drop
        -p:PackageVersion=$GITVERSION_NUGETVERSION

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/drop/*
        name: drop

    - name: Publish to NuGet.org
      if: startsWith(github.ref, 'refs/tags/')
      run: >
        dotnet nuget push "$GITHUB_WORKSPACE/drop/*"
        -k ${{ secrets.NUGET_API_KEY }}
        --skip-duplicate
